  // Provided list of currency codes
const currencyToCountryCode = {
    AED: { code: "AE", name: "🇦🇪 United Arab Emirates Dirham" },
    AFN: { code: "AF", name: "🇦🇫 Afghanistan Afghani" },
    ALL: { code: "AL", name: "🇦🇱 Albania Lek" },
    AMD: { code: "AM", name: "🇦🇲 Armenia Dram" },
    ANG: { code: "AN", name: "🇳🇱 Netherlands Antilles Guilder" },
    AOA: { code: "AO", name: "🇦🇴 Angola Kwanza" },
    ARS: { code: "AR", name: "🇦🇷 Argentina Peso" },
    AUD: { code: "AU", name: "🇦🇺 Australia Dollar" },
    AWG: { code: "AW", name: "🇦🇼 Aruba Florin" },
    AZN: { code: "AZ", name: "🇦🇿 Azerbaijan Manat" },
    BAM: { code: "BA", name: "🇧🇦 Bosnia and Herzegovina Convertible Mark" },
    BBD: { code: "BB", name: "🇧🇧 Barbados Dollar" },
    BDT: { code: "BD", name: "🇧🇩 Bangladesh Taka" },
    BGN: { code: "BG", name: "🇧🇬 Bulgaria Lev" },
    BHD: { code: "BH", name: "🇧🇭 Bahrain Dinar" },
    BIF: { code: "BI", name: "🇧🇮 Burundi Franc" },
    BMD: { code: "BM", name: "🇧🇲 Bermuda Dollar" },
    BND: { code: "BN", name: "🇧🇳 Brunei Dollar" },
    BOB: { code: "BO", name: "🇧🇴 Bolivia Boliviano" },
    BRL: { code: "BR", name: "🇧🇷 Brazil Real" },
    BSD: { code: "BS", name: "🇧🇸 Bahamas Dollar" },
    BTN: { code: "BT", name: "🇧🇹 Bhutan Ngultrum" },
    BWP: { code: "BW", name: "🇧🇼 Botswana Pula" },
    BYN: { code: "BY", name: "🇧🇾 Belarus Ruble" },
    BZD: { code: "BZ", name: "🇧🇿 Belize Dollar" },
    CAD: { code: "CA", name: "🇨🇦 Canada Dollar" },
    CDF: { code: "CD", name: "🇨🇩 Democratic Republic of the Congo Franc" },
    CHF: { code: "CH", name: "🇨🇭 Switzerland Franc" },
    CLP: { code: "CL", name: "🇨🇱 Chile Peso" },
    CNY: { code: "CN", name: "🇨🇳 China Yuan Renminbi" },
    COP: { code: "CO", name: "🇨🇴 Colombia Peso" },
    CRC: { code: "CR", name: "🇨🇷 Costa Rica Colon" },
    CUP: { code: "CU", name: "🇨🇺 Cuba Peso" },
    CVE: { code: "CV", name: "🇨🇻 Cape Verde Escudo" },
    CZK: { code: "CZ", name: "🇨🇿 Czech Republic Koruna" },
    DJF: { code: "DJ", name: "🇩🇯 Djibouti Franc" },
    DKK: { code: "DK", name: "🇩🇰 Denmark Krone" },
    DOP: { code: "DO", name: "🇩🇴 Dominican Republic Peso" },
    DZD: { code: "DZ", name: "🇩🇿 Algeria Dinar" },
    EGP: { code: "EG", name: "🇪🇬 Egypt Pound" },
    ERN: { code: "ER", name: "🇪🇷 Eritrea Nakfa" },
    ETB: { code: "ET", name: "🇪🇹 Ethiopia Birr" },
    EUR: { code: "EU", name: "🇪🇺 Euro" },
    FJD: { code: "FJ", name: "🇫🇯 Fiji Dollar" },
    FKP: { code: "FK", name: "🇫🇰 Falkland Islands Pound" },
    FOK: { code: "FO", name: "🇫🇴 Faroe Islands Krone" },
    GBP: { code: "GB", name: "🇬🇧 United Kingdom Pound" },
    GEL: { code: "GE", name: "🇬🇪 Georgia Lari" },
    GGP: { code: "GG", name: "🇬🇬 Guernsey Pound" },
    GHS: { code: "GH", name: "🇬🇭 Ghana Cedi" },
    GIP: { code: "GI", name: "🇬🇮 Gibraltar Pound" },
    GMD: { code: "GM", name: "🇬🇲 Gambia Dalasi" },
    GNF: { code: "GN", name: "🇬🇳 Guinea Franc" },
    GTQ: { code: "GT", name: "🇬🇹 Guatemala Quetzal" },
    GYD: { code: "GY", name: "🇬🇾 Guyana Dollar" },
    HKD: { code: "HK", name: "🇭🇰 Hong Kong Dollar" },
    HNL: { code: "HN", name: "🇭🇳 Honduras Lempira" },
    HRK: { code: "HR", name: "🇭🇷 Croatia Kuna" },
    HTG: { code: "HT", name: "🇭🇹 Haiti Gourde" },
    HUF: { code: "HU", name: "🇭🇺 Hungary Forint" },
    IDR: { code: "ID", name: "🇮🇩 Indonesia Rupiah" },
    ILS: { code: "IL", name: "🇮🇱 Israel Shekel" },
    IMP: { code: "IM", name: "🇮🇲 Isle of Man Pound" },
    INR: { code: "IN", name: "🇮🇳 India Rupee" },
    IQD: { code: "IQ", name: "🇮🇶 Iraq Dinar" },
    IRR: { code: "IR", name: "🇮🇷 Iran Rial" },
    ISK: { code: "IS", name: "🇮🇸 Iceland Krona" },
    JEP: { code: "JE", name: "🇯🇪 Jersey Pound" },
    JMD: { code: "JM", name: "🇯🇲 Jamaica Dollar" },
    JOD: { code: "JO", name: "🇯🇴 Jordan Dinar" },
    JPY: { code: "JP", name: "🇯🇵 Japan Yen" },
    KES: { code: "KE", name: "🇰🇪 Kenya Shilling" },
    KGS: { code: "KG", name: "🇰🇬 Kyrgyzstan Som" },
    KHR: { code: "KH", name: "🇰🇭 Cambodia Riel" },
    KID: { code: "KI", name: "🇰🇮 Kiribati Dollar" },
    KMF: { code: "KM", name: "🇰🇲 Comoros Franc" },
    KRW: { code: "KR", name: "🇰🇷 South Korea Won" },
    KWD: { code: "KW", name: "🇰🇼 Kuwait Dinar" },
    KYD: { code: "KY", name: "🇰🇾 Cayman Islands Dollar" },
    KZT: { code: "KZ", name: "🇰🇿 Kazakhstan Tenge" },
    LAK: { code: "LA", name: "🇱🇦 Laos Kip" },
    LBP: { code: "LB", name: "🇱🇧 Lebanon Pound" },
    LKR: { code: "LK", name: "🇱🇰 Sri Lanka Rupee" },
    LRD: { code: "LR", name: "🇱🇷 Liberia Dollar" },
    LSL: { code: "LS", name: "🇱🇸 Lesotho Loti" },
    LYD: { code: "LY", name: "🇱🇾 Libya Dinar" },
    MAD: { code: "MA", name: "🇲🇦 Morocco Dirham" },
    MDL: { code: "MD", name: "🇲🇩 Moldova Leu" },
    MGA: { code: "MG", name: "🇲🇬 Madagascar Ariary" },
    MKD: { code: "MK", name: "🇲🇰 North Macedonia Denar" },
    MMK: { code: "MM", name: "🇲🇲 Myanmar Kyat" },
    MNT: { code: "MN", name: "🇲🇳 Mongolia Tughrik" },
    MOP: { code: "MO", name: "🇲🇴 Macau Pataca" },
    MRU: { code: "MR", name: "🇲🇷 Mauritania Ouguiya" },
    MUR: { code: "MU", name: "🇲🇺 Mauritius Rupee" },
    MVR: { code: "MV", name: "🇲🇻 Maldives Rufiyaa" },
    MWK: { code: "MW", name: "🇲🇼 Malawi Kwacha" },
    MXN: { code: "MX", name: "🇲🇽 Mexico Peso" },
    MYR: { code: "MY", name: "🇲🇾 Malaysia Ringgit" },
    MZN: { code: "MZ", name: "🇲🇿 Mozambique Metical" },
    NAD: { code: "NA", name: "🇳🇦 Namibia Dollar" },
    NGN: { code: "NG", name: "🇳🇬 Nigeria Naira" },
    NIO: { code: "NI", name: "🇳🇮 Nicaragua Cordoba" },
    NOK: { code: "NO", name: "🇳🇴 Norway Krone" },
    NPR: { code: "NP", name: "🇳🇵 Nepal Rupee" },
    NZD: { code: "NZ", name: "🇳🇿 New Zealand Dollar" },
    OMR: { code: "OM", name: "🇴🇲 Oman Rial" },
    PAB: { code: "PA", name: "🇵🇦 Panama Balboa" },
    PEN: { code: "PE", name: "🇵🇪 Peru Sol" },
    PGK: { code: "PG", name: "🇵🇬 Papua New Guinea Kina" },
    PHP: { code: "PH", name: "🇵🇭 Philippines Peso" },
    PKR: { code: "PK", name: "🇵🇰 Pakistan Rupee" },
    PLN: { code: "PL", name: "🇵🇱 Poland Zloty" },
    PYG: { code: "PY", name: "🇵🇾 Paraguay Guarani" },
    QAR: { code: "QA", name: "🇶🇦 Qatar Riyal" },
    RON: { code: "RO", name: "🇷🇴 Romania Leu" },
    RSD: { code: "RS", name: "🇷🇸 Serbia Dinar" },
    RUB: { code: "RU", name: "🇷🇺 Russia Ruble" },
    RWF: { code: "RW", name: "🇷🇼 Rwanda Franc" },
    SAR: { code: "SA", name: "🇸🇦 Saudi Arabia Riyal" },
    SBD: { code: "SB", name: "🇸🇧 Solomon Islands Dollar" },
    SCR: { code: "SC", name: "🇸🇨 Seychelles Rupee" },
    SDG: { code: "SD", name: "🇸🇩 Sudan Pound" },
    SEK: { code: "SE", name: "🇸🇪 Sweden Krona" },
    SGD: { code: "SG", name: "🇸🇬 Singapore Dollar" },
    SHP: { code: "SH", name: "🇸🇭 Saint Helena Pound" },
    SLE: { code: "SL", name: "🇸🇱 Sierra Leone Leone" },
    SLL: { code: "SL", name: "🇸🇱 Sierra Leone Leone" },
    SOS: { code: "SO", name: "🇸🇴 Somalia Shilling" },
    SRD: { code: "SR", name: "🇸🇷 Suriname Dollar" },
    SSP: { code: "SS", name: "🇸🇸 South Sudan Pound" },
    STN: { code: "ST", name: "🇸🇹 Sao Tome and Principe Dobra" },
    SYP: { code: "SY", name: "🇸🇾 Syria Pound" },
    SZL: { code: "SZ", name: "🇸🇿 Eswatini Lilangeni" },
    THB: { code: "TH", name: "🇹🇭 Thailand Baht" },
    TJS: { code: "TJ", name: "🇹🇯 Tajikistan Somoni" },
    TMT: { code: "TM", name: "🇹🇲 Turkmenistan Manat" },
    TND: { code: "TN", name: "🇹🇳 Tunisia Dinar" },
    TOP: { code: "TO", name: "🇹🇴 Tonga Pa'anga" },
    TRY: { code: "TR", name: "🇹🇷 Turkey Lira" },
    TTD: { code: "TT", name: "🇹🇹 Trinidad and Tobago Dollar" },
    TVD: { code: "TV", name: "🇹🇻 Tuvalu Dollar" },
    TWD: { code: "TW", name: "🇹🇼 Taiwan Dollar" },
    TZS: { code: "TZ", name: "🇹🇿 Tanzania Shilling" },
    UAH: { code: "UA", name: "🇺🇦 Ukraine Hryvnia" },
    UGX: { code: "UG", name: "🇺🇬 Uganda Shilling" },
    USD: { code: "US", name: "🇺🇸 United States Dollar" },
    UYU: { code: "UY", name: "🇺🇾 Uruguay Peso" },
    UZS: { code: "UZ", name: "🇺🇿 Uzbekistan Som" },
    VES: { code: "VE", name: "🇻🇪 Venezuela Bolivar" },
    VND: { code: "VN", name: "🇻🇳 Vietnam Dong" },
    VUV: { code: "VU", name: "🇻🇺 Vanuatu Vatu" },
    WST: { code: "WS", name: "🇼🇸 Samoa Tala" },
    XAF: { code: "CF", name: "🇨🇫 Central African CFA Franc" },
    XCD: { code: "AG", name: "🇦🇬 Eastern Caribbean Dollar" },
    XDR: { code: "EU", name: "🇪🇺 Special Drawing Rights" },
    XOF: { code: "BJ", name: "🇧🇯 West African CFA Franc" },
    XPF: { code: "PF", name: "🇵🇫 CFP Franc" },
    YER: { code: "YE", name: "🇾🇪 Yemen Rial" },
    ZAR: { code: "ZA", name: "🇿🇦 South Africa Rand" },
    ZMW: { code: "ZM", name: "🇿🇲 Zambia Kwacha" },
    ZWL: { code: "ZW", name: "🇿🇼 Zimbabwe Dollar" }
  };

  export default currencyToCountryCode;